### ISSUE TITLE
RFC006 contact information better distinction between phone numbers

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-specification#68]
There may be high and low prio problems. So perhaps add a phone number for emergency and for normal priority:

```yaml
    ContactInformation:
      type: object
      description: A set of contact information entries
      required:
        - emergencyPhone
        - supportEmail
      properties:
        emergencyPhone:
          type: string
          description: 24/7 available support phone number in case of emergency
        supportPhone:
          type: string
          description: phoneNumber for normal priority support
        supportEmail:
          type: string
          description: email address for normal priority support
```
